<?php 
// Get Date format
if($this->session->userdata('user_date_format')) {
   // If Logged in and session exists
   $custom_date_format = $this->session->userdata('user_date_format');
} else {
   // Get Default date format from /config/cloudlog.php
   $custom_date_format = $this->config->item('qso_date_format');
   }
?>
Dear <?php echo $COL_NAME == "" ? "YL/OM" : $COL_NAME; ?>,

this confirms our 2-way QSO with the following details:

To:   <?php echo $COL_CALL."\n"; ?>
Date: <?php $timestamp = strtotime($COL_TIME_ON); echo date($custom_date_format, $timestamp)."\n"; ?>
Time: <?php $timestamp = strtotime($COL_TIME_ON); echo date("H:i", $timestamp)."\n"; ?>
Band: <?php echo $COL_BAND."\n"; ?>
Mode: <?php echo $COL_MODE."\n"; ?>
Rprt: <?php echo $COL_RST_SENT."\n"; ?>

   vy73 de <?php echo $COL_STATION_CALLSIGN; ?>


<?php echo $COL_STATION_CALLSIGN."\n"; ?>
Loc:  <?php echo $COL_MY_GRIDSQUARE."\n"; ?>
CQ:   <?php echo $COL_MY_CQ_ZONE."\n"; ?>
ITU:  <?php echo $COL_MY_ITU_ZONE."\n"; ?>
<?php if ($COL_MY_IOTA != "") {
   echo "IOTA: ".$COL_MY_IOTA."\n";
}
?>

--
Message generated by Cloudlog
https://github.com/magicbug/Cloudlog
